### ISSUE TITLE
Matching Error

### ISSUE THREAD

**Issue by aycankatitas** [insongkim/PanelMatch#40]
Hello, 
I tried to use PanelMatch on a balanced panel dataset for 3 consecutive U.S. elections (2012,2014,2016). Even though I see possible matches when I plot the Treatment Distribution, the code gave me the following error: 

Error in perform_refinement(lag, time.id, unit.id, treatment, refinement.method,  : 
  no viable treated units for att specification

I suspect this is because I don't have many years in my panel, since I know there are eligible units for matching in 2014. Please let me know how to solve this issue. Thanks!

**Comment by adamrauh** [comment]
@aycankatitas Hm, that is peculiar. The error you're getting is especially odd because it corresponds with a part of the code where it looks for just treated units -- whether or not there are matched controls isn't even relevant at that point. So, any unit that goes from blue to red here should be found. Would you be able to send me either the full data or a part of it and the code you're using to get the error? I really just would need the unit id, time id, and treatment variables from your data. You can send me an email at `adamrauh@mit.edu` if that works so I can look into this more.

**Comment by adamrauh** [comment]
should be fixed in [this](https://github.com/insongkim/PanelMatch/commit/a6bfc0c010ae1cca7f3e860e99ace13735e51d93) commit

**Comment by NaijiaLiu** [comment]
I had the same issue - I think the problem is that for us, the unit.id was not integer from 1:N. instead, we had non-contiuous id for each unit such as 1239827450983.

**Comment by Architesh** [comment]
I have the same type of error: Error in panel_match(lag, time.id, unit.id, treatment, refinement.method,  : 
  please convert time id to consecutive integers. I tried many different ways. No success yet. While my data is alright checked many many times. The error still occurs and i am struck. In one file it is working in other file it does not.
